version: '3'
services:
  wiremock:
    image: rodolpheche/wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./stubs:/home/wiremock
    command:
       --root-dir /home/wiremock
       --verbose
